ng.module('nougat.components')
.requires(
'nougat.components.position',
'nougat.components.size',
'nougat.components.color',
'nougat.components.geometry',
'nougat.components.material',
'nougat.components.mesh'
).defines();